In [28]:
import numpy as np

In [26]:
arr1D = np.array([1 , 2 , 5 , 7 , 8]) # 1D Array

In [25]:
print(arr1D)

[1 2 5 7 8]


In [24]:
arr2D = np.array([[1 , 2 , 3] , [4 , 5 , 6]]) # 2D Array

In [23]:
print(arr2D)

[[1 2 3]
 [4 5 6]]


In [22]:
arr3D = np.array([[[1 , 2 , 3] , [4 , 5 , 6] , [7,  8 , 9]] , [[1 , 2 , 3] , [4 , 5 , 6] , [ 7, 9 , 10]]]) # 3D Array

In [21]:
print(arr3D)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[ 1  2  3]
  [ 4  5  6]
  [ 7  9 10]]]


In [20]:
print(arr3D.shape) #Get array dimension.

(2, 3, 3)


In [19]:
arr4D = np.array([[[[1 , 2 , 3] , [5 , 6 , 7]]] , [[[5 , 6 , 7] , [9 , 10 , 11]]]]) # 4D Array

In [18]:
print(arr4D)

[[[[ 1  2  3]
   [ 5  6  7]]]


 [[[ 5  6  7]
   [ 9 10 11]]]]


In [17]:
print(arr4D.shape) #Get array dimension.

(2, 1, 2, 3)


In [16]:
arr0s = np.zeros((3,3,3) , dtype=int)#return 3DArray of Zeros with type int because default is float

In [15]:
print(arr0s)

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]


In [14]:
arr1s = np.ones((3,3) , dtype=int)#return 2DArray of Ones with type int because default is float

In [13]:
print(arr1s)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [12]:
arrRange = np.arange(10) #1D Array with range from 0-9

In [11]:
print(arrRange)

[0 1 2 3 4 5 6 7 8 9]


In [10]:
arrWithCount = np.linspace(0 , 10 , 30) #return 1DArray range from 0-10 with count 30 element

In [9]:
print(arrWithCount)

[ 0.          0.34482759  0.68965517  1.03448276  1.37931034  1.72413793
  2.06896552  2.4137931   2.75862069  3.10344828  3.44827586  3.79310345
  4.13793103  4.48275862  4.82758621  5.17241379  5.51724138  5.86206897
  6.20689655  6.55172414  6.89655172  7.24137931  7.5862069   7.93103448
  8.27586207  8.62068966  8.96551724  9.31034483  9.65517241 10.        ]


In [8]:
arrRandom = np.random.rand(3,3,2) #Return 3DArray with 3rows and 2column

In [7]:
print(arrRandom)

[[[0.39082349 0.3200437 ]
  [0.57397873 0.34406694]
  [0.08462491 0.0338331 ]]

 [[0.53296917 0.01048985]
  [0.30546301 0.51131314]
  [0.25400538 0.64220699]]

 [[0.01192455 0.23628958]
  [0.38863988 0.2864922 ]
  [0.35707852 0.32961436]]]
